reconnect_timeout: 60

# CML5 server
server: 10.20.0.50:8080

devices:
  # Normalni studna
  # - token: y9fMRfFTLuBhdvz7gsrj
  #   type: studna2
  #   variant: single
  #   up_speed: 0.001
  #   down_speed: 0.0005

  # Studna se dvema vystupy
  # - token: KJ4HOWsSoBIuL8A3ZbOM
  #   type: studna2
  #   variant: duo
  #   up_speed: 0.02
  #   down_speed: 0.005

  # Studna max
  # - token: f7bONoV9xa7XxPlfbmnL
  #   type: studna2
  #   variant: max
  #   up_speed: 0.01
  #   down_speed: 0.001

  # Studna solar
  # - token: AhxGKXmzpgALMMdJIWDL
  #   type: studna2
  #   variant: solar
  #   up_speed: 0.0003
  #   down_speed: 0.0001

  # Normalni studna na CML5
    - token: Z9SIKTeHh7MaTNzzjcbv
      type: studna2
      variant: single
      up_speed: 0.001
      down_speed: 0.0005
