reconnect_timeout: 60

# CML5 server
server: cml5.seapraha.cz

devices:

        
  # Druha studna max
  - token: D4sdtGLQ1TjcWxNpkDNa
    type: studna2
    variant: max
    up_speed: 0.01
    down_speed: 0.001
