reconnect_timeout: 60

# CML5 server
server: cml5.seapraha.cz

devices:

        
  # Studna se dvema vystupy
  - token: xOg21HspD7MGlndbjN53
    type: studna2
    variant: duo
    up_speed: 0.02
    down_speed: 0.005

